@echo off 
SET INCLUDES=-I ..\ext
SET SRC=..\src\lister.c
SET WARNING_FLAGS=-W4 -WX -wd4100 -wd4101 -wd4189 -wd4996 -wd4530 -wd4201 -wd4505 -wd4098 -wd4700 -wd4127
SET COMPILER_FLAGS=-nologo -FC  %WARNING_FLAGS% %INCLUDES% -Fe:Lister.exe
SET LINKER_FLAGS=-SUBSYSTEM:CONSOLE Shlwapi.lib

IF NOT EXIST build MKDIR build
PUSHD build
CL %COMPILER_FLAGS% -MDd -Zi %SRC% -DDEVELOPER -link %LINKER_FLAGS%
COPY *.exe ..

POPD
